services:
  - type: web
    name: stvds-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT --timeout 300 app:app
    disk:
      name: stvds-data
      mountPath: /opt/render/project/src/data
      sizeGB: 10